name: signalbyt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.100+100

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.1
  firebase_crashlytics: ^3.0.6
  flutter_local_notifications: ^16.1.0
  provider: ^6.0.2
  path_provider: ^2.0.2
  hive: ^2.0.4
  get: ^4.6.5
  dio: ^5.2.0
  flutter_spinkit: ^5.1.0
  modal_bottom_sheet: ^2.0.1
  google_sign_in: ^6.0.1
  sign_in_with_apple: ^5.0.0
  package_info_plus: ^5.0.1
  flutter_animated_dialog: ^2.0.1
  flutter_styled_toast: ^2.1.3
  url_launcher: ^6.1.4
  shimmer: ^3.0.0
  configurable_expansion_tile_null_safety: ^3.1.1
  json_annotation: ^4.0.0
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons.git
      branch: null-safety-migration
  share_plus: ^7.2.1
  purchases_flutter: ^6.2.0
  image_picker: ^1.0.0
  cached_network_image: ^3.2.0
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.3
  flutter_native_splash: ^2.2.16
  easy_localization: ^3.0.1
  flutter_dotenv: ^5.0.2
  flutter_widget_from_html_core: ^0.14.7
  fwfh_webview: ^0.14.2
  webview_flutter: ^4.0.5
  flutter_svg: ^2.0.2
  google_fonts: ^5.1.0
  socket_io_client: ^2.0.0
  custom_navigation_bar: ^0.8.2
  unity_ads_plugin: ^0.3.13
  unity_mediation: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.0.4
  #flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  remove_alpha_ios: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svg/
    - assets/translations/
