update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
		ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "bwmr-kncm-fnym-qpek"
  end

  desc "upload meta"
  lane :metadata do
    deliver(
      submit_for_review: false,
      skip_binary_upload: true,
      force: true,
      metadata_path: "./metadata"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :test_flight do
    build_app(clean: true, workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
       skip_waiting_for_build_processing: true
    )
  end


  desc "Push a new beta build to TestFlight"
  lane :production do
    deliver(
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
